travis: Make OSX build work again by not installing pkgconfig.
Recent builds are failing with the following error:

    Error: pkg-config 0.29.2 is already installed

Assuming this will be the case form now on, we don't have to install
pkgconfig anymore.